<?php

declare(strict_types=1);

namespace VelvetCMS\Commands\Route;

use VelvetCMS\Commands\Command;
use VelvetCMS\Core\Application;

class CacheCommand extends Command
{
    public function __construct(
        private readonly Application $app
    ) {}

    public function signature(): string
    {
        return 'route:cache';
    }

    public function description(): string
    {
        return 'Cache the route definitions for faster routing';
    }

    public static function category(): string
    {
        return 'Optimization';
    }

    public function handle(): int
    {
        $this->info('Caching routes...');

        $router = $this->app->make('router');
        $cacheFile = storage_path('cache/routes.php');

        $routes = require base_path('routes/web.php');
        $routes($router, $this->app);

        $routeDefinitions = $router->getRouteDefinitions();

        if (empty($routeDefinitions)) {
            $this->warning('No routes found to cache.');
            return 1;
        }

        $cacheDir = dirname($cacheFile);
        if (!is_dir($cacheDir)) {
            mkdir($cacheDir, 0755, true);
        }

        $export = var_export($routeDefinitions, true);
        $content = <<<PHP
<?php

declare(strict_types=1);

/**
 * Cached route definitions
 * Generated: {$this->timestamp()}
 * 
 * This file is auto-generated by 'velvet route:cache'
 * Do not edit manually - changes will be overwritten.
 */

return {$export};

PHP;

        file_put_contents($cacheFile, $content);

        $count = count($routeDefinitions);
        $this->success("Cached {$count} route definitions.");
        $this->line("Cache file: {$cacheFile}");

        return 0;
    }

    private function timestamp(): string
    {
        return date('Y-m-d H:i:s');
    }
}
